version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands: 
      - npm ci
  
  build:
    commands:
      - npx cypress run --env environmentName=prod || true
  
  post_build:
    commands:
      - npm run report: merge
      - npm run report: generate

env: 
  secrets-manager:
    CYPRESS_EMAIL: "cypress/creds:EMAIL"
    CYPRESS_PASSWORD: "cypress/creds:PASSWORD"
    CYPRESS_USRENAME: "cypress/creds:USERNAME"

artifacts:
  files:
    - '**/*'
    base-directory: cypress/resports/mochawesome