name: Cypress Tests

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --env environmentName=prod
        env:
          CYPRESS_EMAIL: ${{ secrets.EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
        continue-on-error: true   

      - name: Merge reports
        if: always()
        run: npm run report:merge

      - name: Generate HTML report
        if: always()
        run: npm run report:generate

      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-report
          path: cypress/reports/mochawesome
          retention-days: 5